### ISSUE TITLE
Does not work on Fabric Loom, Gradle 8.8, Java 17

### ISSUE THREAD

**Issue by rikka0w0** [TheMrMilchmann/gradle-curseforge-publish#37] opened 2024-07-30 07:25 UTC
The following is my `build.gradle`:
```
plugins {
	id 'fabric-loom' version '1.7-SNAPSHOT'
	id 'maven-publish'
	id 'io.github.themrmilchmann.curseforge-publish' version '0.6.1'
}

curseforge {
    apiToken = 'MY_TOKEN'
    publications {
        register("curseForge") {
            projectId = "336554"

            artifacts.register("main") {
                from(tasks.named("remapJar"))
            }
        }
    }
}
System.out.println(curseforge.publications.getByName("curseForge").projectId.get())
```

When I run, it get:
```
.\gradlew.bat publishToCurseForge
To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.8/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation.
Daemon will be stopped at the end of the build

> Configure project :
Fabric Loom: 1.7.2
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
336554

> Task :publishFabricPublicationToCurseForge FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishFabricPublicationToCurseForge'.
> Cannot query the value of property 'projectId' because it has no value available.
```

The `System.out.println` prints the correct projected, but curseforge-publish cannot recognize it.

**Comment by TheMrMilchmann** [comment] 2024-07-30 08:43
Hi @rikka0w0,
when the plugin is used together with mod development plugins (such as Loom, or NeoGradle), preconfigured publications with the appropriate artifacts are created automatically. You can read more about this in the [Interoperability section of the README](https://github.com/TheMrMilchmann/gradle-curseforge-publish?tab=readme-ov-file#interoperability).

In your case, you'll want to change the configuration of your publication too:

```kotlin
curseforge {
    publications {
        named("fabric") {
            projectId = "336554"

            artifacts.named("main") {
                // No need to add the jar here. It is preconfigured.
                // ...
            }
        }
    }
}
```

Specifically, the section about [Loom interop](https://github.com/TheMrMilchmann/gradle-curseforge-publish?tab=readme-ov-file#fabricloom) will be of interest to you.

[Also, here is an example of how I configure the publication for one of my mods.](https://github.com/TheMrMilchmann/AE2CCBridge/blob/bbad6d5fc650899e9ef9707e561c48df975dd717/build.gradle.kts#L40-L61)

**Comment by rikka0w0** [comment] 2024-08-01 17:59
Thanks!

This script snippet solves the projectId not available issue. However, if I have the changelog section, it fails with `Could not determine the dependencies of task ':publishFabricPublicationToCurseForge'.`. Without it, the script works. My curseforge section now looks like this:

```
curseforge {
	apiToken="SECRETE"
	publications {
		named("fabric") {
			projectId = "336554"

			artifacts.named("main") {
				displayName = "${project.minecraft_version}-${project.mod_version}-fabric"
				releaseType = ReleaseType.BETA

				changelog {
					format = ChangelogFormat.MARKDOWN
					from(file('build/info/CHANGELOG_FULL.md'))
				}
			}
		}
	}
}
```

May I ask one more question? How to specify the dependencies? I read that I need to use "slug" instead of projectId to specify dependencies. How could I find the slug? For example, my mod depends on Fabric API.

Does the Loom integration automatically locate the dependencies? I would like to know how to manually specify the versions of the dependencies.

Thanks in advance!

**Comment by TheMrMilchmann** [comment] 2024-08-01 18:50
What's happening here is that you're using the `from(...)` function from `CurseForgePublicationArtifact` (which is used to specify the artifact file) instead of setting the changelog's content.

I assume you followed an example from the README which is currently wrong (See #38). Instead, you should declare the changelog as follows:

```kotlin
changelog {
    format = ...
    content = file('build/info/CHANGELOG_FULL.md").readText()
}
```

I think the Groovy equivalent is `content = file('build/info/CHANGELOG_FULL.md').text`.


> May I ask one more question? How to specify the dependencies? I read that I need to use "slug" instead of projectId to specify dependencies. How could I find the slug? For example, my mod depends on Fabric API.

The slug is part of the URL of your mods CurseForge page:

    https://www.curseforge.com/minecraft/mc-mods/{slug}

For example, for `https://www.curseforge.com/minecraft/mc-mods/fabric-api` the slug would be `fabric-api`.


> Does the Loom integration automatically locate the dependencies

No, this is currently not possible since information about CurseForge publications is not available in mod artifacts.


> I would like to know how to manually specify the versions of the dependencies.

CurseForge does not support dependencies on specific versions of a mod.

**Comment by rikka0w0** [comment] 2024-08-02 13:00
> For example, for https://www.curseforge.com/minecraft/mc-mods/fabric-api the slug would be fabric-api.

Thanks! The dependency part is now working.

However, if I have `releaseType = ReleaseType.BETA` or `changelog { format = ChangelogFormat.MARKDOWN }`, the same error happens:
```
* What went wrong:
Could not determine the dependencies of task ':publishFabricPublicationToCurseForge'.
> Could not create domain object 'main' (CurseForgePublicationArtifact)
```

If I only have `changelog { file('build/info/CHANGELOG_FULL.md').text }`, the publish works as expected. I'm pretty sure that `releaseType = ReleaseType.BETA` is causing the issue.

This is my current working script.
```
curseforge {
	apiToken="SECRETE"
	publications {
		named("fabric") {
			projectId = "336554"

			artifacts.named("main") {
				displayName = "${project.minecraft_version}-${project.mod_version}-fabric"
				// releaseType = ReleaseType.BETA

				changelog {
					//format = ChangelogFormat.MARKDOWN
					content = file('build/info/CHANGELOG_FULL.md').text
				}

				relations {
				 	requiredDependency("fabric-api")
				}
			}
		}
	}
}
```

**Comment by TheMrMilchmann** [comment] 2024-08-19 07:11
> > For example, for https://www.curseforge.com/minecraft/mc-mods/fabric-api the slug would be fabric-api.
> 
> Thanks! The dependency part is now working.
> 
> However, if I have `releaseType = ReleaseType.BETA` or `changelog { format = ChangelogFormat.MARKDOWN }`, the same error happens:
> 
> ```
> * What went wrong:
> Could not determine the dependencies of task ':publishFabricPublicationToCurseForge'.
> > Could not create domain object 'main' (CurseForgePublicationArtifact)
> ```
> 
> If I only have `changelog { file('build/info/CHANGELOG_FULL.md').text }`, the publish works as expected. I'm pretty sure that `releaseType = ReleaseType.BETA` is causing the issue.
> 
> This is my current working script.
> 
> ```
> curseforge {
> 	apiToken="SECRETE"
> 	publications {
> 		named("fabric") {
> 			projectId = "336554"
> 
> 			artifacts.named("main") {
> 				displayName = "${project.minecraft_version}-${project.mod_version}-fabric"
> 				// releaseType = ReleaseType.BETA
> 
> 				changelog {
> 					//format = ChangelogFormat.MARKDOWN
> 					content = file('build/info/CHANGELOG_FULL.md').text
> 				}
> 
> 				relations {
> 				 	requiredDependency("fabric-api")
> 				}
> 			}
> 		}
> 	}
> }
> ```

After further testing, I can't reproduce the error you are having. It would be great if you could share more details about your build setup or provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by TheMrMilchmann** [comment] 2024-09-10 08:35
After looking at @NyakoFox's project linked in #52, I wonder if you import the required types. When referencing either `ChangelogType` or `ReleaseType`, make sure to add the required import (`import io.github.themrmilchmann.gradle.publish.curseforge.*`) add the top of your build scripts.

IDEA seems to struggle a bit with suggesting that in Groovy.

**Comment by TheMrMilchmann** [comment] 2024-11-28 20:15
Closing this as I'm still unable to reproduce and this is likely caused by a missing import.

The implementation of a warning when implicit publications are not configured is tracked in #53 but I have no immediate plans to work on that.

**Closed by TheMrMilchmann** 2024-11-28 20:15 UTC
Labels: was:invalid, a:question
